### PR TITLE
Integrating `@matrixai/events` into ESM 2.x

### PR DESCRIPTION
**Pull request by CMCDragonkai**
### Description

The ESM branch needs events and keep up with the 1.9.x.

This currently doesn't yet work because `js-events` isn't ESM native yet. So have to wait until that is the case.

This branch must be kept up to date with the branch `feature-events`. https://github.com/MatrixAI/js-async-init/tree/feature-events

### Tasks

- [x] 1. Update the `@matrixai/events` to the ESM-native version when available
- [x] 2. Run tests again to see if everything works

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
The `feature-events` branch is now on `1.10.0`. So it's evolved quite a bit. The `2.x` releases will need a major update to bring all the changes.

**Comment by CMCDragonkai** [comment]
All the commits here https://github.com/MatrixAI/js-async-init/commits/feature-events will need to be redone on `staging` with ESM changes so that way the history looks right.

**Comment by CMCDragonkai** [comment]
When migrating to ESM, we might as well change over to #22 too.

**Comment by amydevs** [comment]
some notes regarding windows failing CI/CD due to chocolatey v2.0

The windows before_build script should have this include so that `refreshenv` will resolve to the powershell alias:

```yml
before_script:
    - mkdir -Force "$CI_PROJECT_DIR/tmp"
    # so that refreshenv will resolve to the correct Powershell alias
    - Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
```

choco-install.ps1 should have the package name changed to `nodejs` instead of `nodejs.install`. As the former is a dependent of the latter, installing a newer version of the latter directly will make chocolatey complain that it will conflict with dependents.

```powershell
# Install nodejs v20.5.1 (will use cache if exists)
$nodejs = "nodejs"
choco install "$nodejs" --version="20.5.1" --require-checksums -y
```

related: https://github.com/chocolatey/choco/issues/3176

**Comment by CMCDragonkai** [comment]
Yes that needs to be applied across the repos otherwise CI on windows will start failing.

**Comment by CMCDragonkai** [comment]
So the `feature-events` is maintaining the older commonjs version. While staging is currently on ESM.

This PR needs to merge into staging and release another 2.x version in order to keep up to date with the 1.x version that is being branched off in `feature-events`.

**Comment by CMCDragonkai** [comment]
> some notes regarding windows failing CI/CD due to chocolatey v2.0
> 
> The windows before_build script should have this include so that `refreshenv` will resolve to the powershell alias:
> 
> ```yaml
> before_script:
>     - mkdir -Force "$CI_PROJECT_DIR/tmp"
>     # so that refreshenv will resolve to the correct Powershell alias
>     - Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
> ```
> 
> choco-install.ps1 should have the package name changed to `nodejs` instead of `nodejs.install`. As the former is a dependent of the latter, installing a newer version of the latter directly will make chocolatey complain that it will conflict with dependents.
> 
> ```powershell
> # Install nodejs v20.5.1 (will use cache if exists)
> $nodejs = "nodejs"
> choco install "$nodejs" --version="20.5.1" --require-checksums -y
> ```
> 
> related: [chocolatey/choco#3176](https://github.com/chocolatey/choco/issues/3176)

I've just done this in https://github.com/MatrixAI/js-events/commit/849bc20087dc5ae154f8e50a0f94369eaa3133f6

**Comment by CMCDragonkai** [comment]
Actually it might not work anymore. We might need to also change our windows build tags to:

```
  tags:
    - saas-windows-medium-amd64
```

At the time I saw the pipeline run, no windows runners were available. This may be a temporary change until we move to GitHub actions.

**Comment by CMCDragonkai** [comment]
Yep now it works: https://github.com/MatrixAI/js-events/commit/9de0ee517f8847eeb8c71e65cb47c4e22872903e - this needs to be done for all repos @tegefaulkes @amydevs.

**Comment by CMCDragonkai** [comment]
> Yep now it works: [MatrixAI/js-events@9de0ee5](https://github.com/MatrixAI/js-events/commit/9de0ee517f8847eeb8c71e65cb47c4e22872903e) - this needs to be done for all repos @tegefaulkes @amydevs.

@aryanjassal how fast are we changing to github so we don't have to do this?

**Comment by CMCDragonkai** [comment]
Merging, this will be released as 2.1.0 in staging.

**Pull request merged**
