### PR TITLE
Fix for blocking `ready` causing false not running/destroyed errors

### LINKED ISSUE #7: Allow ready decorator to opt in to being callable with allowed status "exceptions"
### Specification

The `ready` decorator right now prevents execution unless the class is ready, that is after `start` is finished, and before `stop` is called.

The problem here is that there are many methods that need to be callable publically and therefore has `ready` applied, but also needs to be called in the `start` method.

Of course the reason for this is to prevent inadvertent usage of the public method when the side-effects of `start` hasn't completed. However in some situations, the programmer can be responsible for ordering the side-effects in the `start` method.

So the `ready` method should have an additional parameter to allow it to run in the other statuses other than `_running`.

Note that this parameter would make `block` not work. Because `block` ensures that the function would wait until the `initLock` is freed, as the ready methods acquire a read lock.

This parameter can be called:

```ts
// ready(errorNotRunning, block, allowedStatuses: Array<Status>)
ready(error, false, ['starting'])
```

Then you can allow a ready method to also be called when it is `'destroying'`, `'starting'` or `'stopping'` or `null`.

Note that `null` means that the none of the statuses are occurring. So generally speaking, allowing `null` means that it is also allowed when the class itself isn't starting, stopping or destroying, and whether or not is running.

Right now the methods are doing this:

```
if (this[initLock].isLocked()) {
  throw errorNotRunning;
}
if (!this[_running]) {
  throw errorNotRunning;
}
```

The above would need to change to allow the statuses as exceptions, even if the init lock is locked, or that running isn't true.

### Additional context

* https://github.com/MatrixAI/js-polykey/pull/310 - affects `syncNodeGraph`, if this can be done, this call be part of the `start()` call of `NodeConnectionManager` rather than being a separate call.

### Tasks

1. ...
2. ...
3. ...

### PR DESCRIPTION
**Pull request by emmacasolin**
### Description

Ready functions checking if whether the `initLock` is locked. This conflicts with the ready-blocking functions. Instead we should be checking if the status is not `null`, because that's the only status where an initialisation action isn't occurring (destroying, starting, stopping).

At the same time, we should be able to fix #7 since that also requires some `allowedStatuses` as an exception which allows the programmer to order the side-effects when calling these functions inside `start`, `stop` or `destroy`.

### Issues Fixed

* Fixes #7
* Fixes conflict bug in https://github.com/MatrixAI/js-polykey/pull/381#issuecomment-1161105074

### Tasks

- ~[x] 1. Change check for `this[initLock].isLocked()` in `ready` to `this[_status] !== null` for all classes~ - this is not sufficient, we do need to check for locking, but specify only when `write` is locked
- ~[ ] 2. Fix tests that previously relied on `[initLock]` being locked before the `stop`/`destroy` is awaited~ - not necessary because of task 7.
- [x] 3. Fixed where we are `yield*` without `return`. These should all be `return yield*` to ensure that the generator's return value is also returned.
- [x] 4. Enabled `allowedStatuses` which is by default `[]`, but the programmer can set it to be `['starting']` to enable the function to also be called inside the `start` method. When doing this, the `block` parameter is ignored.
- [x] 5. Added tests to prevent regression of where concurrently calling ready-blocking method and ready methods results in a conflict. - https://github.com/MatrixAI/js-async-init/pull/12#issuecomment-1161263347
- [x] 6. Use `stack = new Error().stack`, no need for `?? ''`, since stack could be undefined.
- [x] 7. Upgrade `js-async-locks` to be able to use `isLocked('write')`.
- [x] 8. Add tests for testing `allowedStatuses` usage
- [x] 9. Add tests for testing `return yield*`

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [ ] Sanity check the final build

### CODE REVIEW

**Comment by emmacasolin** [comment]
The tests that check for the `ErrorNotRunning` etc. exceptions to be thrown during `stop`/`destroy` now fail, since they call the `stop`/`destroy` after calling the `ready`-decorated method, e.g.
```ts
await x.start();
await expect(
  (async () => {
    const stop = x.stop();
    x.doSomethingSync();
    await stop;
  })(),
).rejects.toThrow(ErrorAsyncInitNotRunning);
```

Previously when we were checking `this[initLock]` they would still throw, since the `const stop = x.stop();` still returned `this[initLock].withWriteF(async () => {...}`, but the status symbol isn't changed until we actually await the stop. Not sure what we want to do here.

**Comment by CMCDragonkai** [comment]
This is because `doSomethingSync()` runs before the locked callback runs. Technically it is correct for it to now throw an exception, because the stop hasn't really started yet. As in the function call to `stop` has occurred, but the internal async operation hasn't started. SO the test can be changed.

**Comment by CMCDragonkai** [comment]
To solve this problem, I also want to solve #7 at the same time, so I'm adding some changes to this PR to do this. So I'll take over this PR for the moment.

**Comment by CMCDragonkai** [comment]
New tests should be added in to prevent regression of https://github.com/MatrixAI/js-polykey/pull/381#issuecomment-1161105074.

It should be something like:

```ts
class C {
  @ready(..., true)
  async f() { ... }

  @ready(...)
  async g() { ... }
}

const c = new C();

const fP = c.f();
const gP = c.g(); // <- should not throw an exception
await fP;
await gP;
```

**Comment by CMCDragonkai** [comment]
Ok there's a problem with only checking the status and not the lock.

It affects asynchronous functions too.

Because `x.doSomethingAsync()` does the status check synchronously, that runs before `stop()` acquires the lock too. So unless `x.doSomethingAsync()` is wrapped in a `setTimeout` delay, it will always run the status check before `stop` acquires the lock.

The problem here is that the ready wrapper returns the asynchronous internal function with `return f.apply(this, args);`.

This means you, by checking just the status, it's possible that the status is `null`, and then you proceed to run your asynchronous function, while the `stop` function body is also running, and then we don't have mutual exclusion. Things may still work due to the single-threadedness of JS, but it is not guaranteed.

So we do need to check the lock somehow.

I think we need to do this a little different. Maybe we do need to check the lock, but this time we check if it is  write lock or read lock. If it is read lock, we don't care, but if it is a write lock, then we should be throw the exception.

**Comment by CMCDragonkai** [comment]
So what we need is `isLocked(type?: 'read' | 'write)`. By default it will check both which is how it is done right now, but then we can also focus on only checking if it is read locked or write locked.

**Comment by CMCDragonkai** [comment]
Then instead of checking status, we will check `isLocked('write')`. Which would indicate to us that the init lock is infact "changing", and that means we cannot be calling the function.

Meaning our check becomes:

```ts
          if (this[initLock].isLocked('write') || !this[_running]) {
            errorNotRunning.stack = new Error().stack;
            throw errorNotRunning;
          }
```

**Comment by CMCDragonkai** [comment]
Another alternative is to check the `writeCount` if you do this, you can also distinguish if a `start`, `stop` or `destroy` is being called while the being locked.

Kind of like `this[initLock].isLocked() && this[initLock].writerCount > 0`.

**Comment by CMCDragonkai** [comment]
I've updated js-async-locks with the ability to do `isLocked('write')`. Please attempt to use it instead of checking the status. This way we can throw an exception only if `this[initLock].isLocked('write') || !this[_running]`.

Please also update the other `CreateDestroy` and `CreateDestroyStartStop` accordingly.

I've also testing out the new staging system for js-async-locks, so no release version just yet, if it doesn't work, just push out a release yourself for async-locks and update here.

**Comment by CMCDragonkai** [comment]
Still to do:

1. Change to using `isLocked('write')`
2. The tests that I fixed in order to deal with status check should be reverted, we should have our original test behaviour with `isLocked('write')`
3. Add in a regression test for https://github.com/MatrixAI/js-async-init/pull/12#issuecomment-1161263347 for all 3 variants
4. Add in testing for the `return yield*` that I've added in, to ensure that the ready decorated generator is also propagating the return value.

**Comment by CMCDragonkai** [comment]
Async-locks is merged. Pending release of 2.3.0 now.

**Comment by CMCDragonkai** [comment]
Ok even with `isLocked('write')` we end up with the same issue as checking for status. The async function still runs if `stop()` is called.

I think the only solution here is to use `writerCount()`.

There's only one problem, if one were to call `x.start()` again, it's possible that in the split second of time, it's possible that that this would cause an issue with the async function.

It seems the solution here is to say that calling `x.stop()` doesn't immediately prevent all ready operations. It only prevents it when the `x.stop()` gets the lock. If you call a ready function prior, it will still work. Unless the ready function prior is slowed down. So basically there's some non-determinism here. If you really want to prevent `stop()` from concurrently working, then you must use ready with block.

I think that's what we will have to expect from now on.

**Comment by CMCDragonkai** [comment]
Actually I think there's a solution, but it may not work for `RWLockReader`. Since we're not using that, I may decide to remove that class entirely.

**Comment by CMCDragonkai** [comment]
Ok only `RWLockWriter` has a useful `isLocked(type)`. The `RWLockReader` will be left as is, but without the `type` ability. It's not important to solve atm, it can be done but nobody is using `RWLockReader`.

**Comment by CMCDragonkai** [comment]
2.3.1 is pending release for js-async-locks. Will bring this in here.

**Comment by CMCDragonkai** [comment]
This is ready!

**Comment by CMCDragonkai** [comment]
@emmacasolin @tegefaulkes released this as 1.8.0.

This should be updated on PK and all other libraries that use async-init. Behaviour should be as expected now.

**Pull request merged**
